export const ms = [

    {
      time: 1710840672929,
      message: 'I am try out this new BBQ recipe, I think this might be amazing',
      from: {
        role: "owner",
        displayName: "Goldlabel",
        avatar: "/svg/iOS.svg"
      },
    },
    {
      time: 1710840632320,
      message: `Do you have a suggestion for a good present for John on his work
        anniversary. I am really confused & would love your thoughts on it.`,
      from: {
        role: "customer",
        displayName: "Chix",
        avatar: "/svg/characters/chix.svg"
      },
    },
    {
      time: 1710840603827,
      message: "I'll be in the neighbourhood this week. Let's grab a bite to eat",
      from: {
        role: "owner",
        displayName: "Goldlabel",
        avatar: "/svg/iOS.svg"
      },
    },
    {
      time: 1710840756794,
      message: 'I have the tickets to the ReactConf for this year.',
      person: '/static/images/avatar/3.jpg',
      from: {
        role: "customer",
        displayName: "Chix",
        avatar: "/svg/characters/chix.svg"
      },
    },
    {
      time: 1710840940244,
      message: 'My appointment for the doctor was rescheduled for next Saturday.',
      from: {
        role: "owner",
        displayName: "Goldlabel",
        avatar: "/svg/iOS.svg"
      },
    },
    {
      time: 1710842230157,
      message: `Menus that are generated by the bottom app bar (such as a bottom
        navigation drawer or overflow menu) open as bottom sheets at a higher elevation
        than the bar.`,
      from: {
        role: "customer",
        displayName: "Chix",
        avatar: "/svg/characters/chix.svg"
      },
    },
]