export const namesByLetter: {[key: string]: string[]} = {
  A: ["Alice", "Alexander", "Amelia"],
  B: ["Benjamin", "Bella", "Brandon"],
  C: ["Charlotte", "Caleb", "Clara"],
  D: ["Daniel", "David", "Daisy"],
  E: ["Emma", "Ethan", "Eleanor"],
  F: ["Faith", "Finn", "Freya"],
  G: ["Grace", "Gabriel", "Georgia"],
  H: ["Henry", "Hannah", "Harper"],
  I: ["Isabella", "Isaac", "Ivy"],
  J: ["James", "Jessica", "Jack"],
  K: ["Katherine", "Kevin", "Kylie"],
  L: ["Liam", "Lily", "Lucas"],
  M: ["Mia", "Michael", "Madison"],
  N: ["Noah", "Natalie", "Nathan"],
  O: ["Olivia", "Owen", "Oliver"],
  P: ["Penelope", "Patrick", "Phoebe"],
  Q: ["Quinn"],
  R: ["Ryan", "Rachel", "Rebecca"],
  S: ["Sophia", "Samuel", "Sarah"],
  T: ["Thomas", "Taylor", "Tessa"],
  U: ["Uma"],
  V: ["Victoria", "Vincent", "Violet"],
  W: ["William", "Willow", "Wesley"],
  X: ["Xavier"],
  Y: ["Yasmine", "Yara", "Yvette"],
  Z: ["Zachary", "Zoe", "Zara"]
};
